index:
    path: /
    controller: App\Controller\DefaultController::index
boutique:
    path: /boutique
    controller: App\Controller\front\BoutiqueController::boutique
produit:
    path: /produit
    controller: App\Controller\DefaultController::produit
connexion:
    path: /connexion
    controller: App\Controller\UserSecurityController::login
register:
    path: /inscription
    controller: App\Controller\DefaultController::register
contact:
    path: /contact
    controller: App\Controller\DefaultController::contact
panier:
    path: /panier
    controller: App\Controller\DefaultController::panier
membre:
    path: /membre
    controller: App\Controller\DefaultController::membre
administrateur:
    path: /administrateur
    controller: App\Controller\SecurityController::login
admin_produit:
    path: /administrateur/produit
    controller: App\Controller\DefaultController::admin_produit
admin_promo:
    path: /administrateur/promo
    controller: App\Controller\DefaultController::admin_promo
admin_commande:
    path: /administrateur/commande
    controller: App\Controller\DefaultController::admin_commande
detail_commande:
    path: /administrateur/detail_commande
    controller: App\Controller\DefaultController::detail_commande
detail_client:
    path: /administrateur/detail_client
    controller: App\Controller\DefaultController::detail_client
admin_client:
    path: /administrateur/client
    controller: App\Controller\DefaultController::admin_client
admin_categorie:
    path: /administrateur/categorie
    controller: App\Controller\DefaultController::admin_categorie
admin_souscategorie:
    path: /administrateur/souscategorie
    controller: App\Controller\DefaultController::admin_souscategorie
produit_add:
    path: /administrateur/produit/add
    controller: App\Controller\DefaultController::produit_add
promo_add:
    path: /administrateur/promo/add
    controller: App\Controller\DefaultController::promo_add
categorie_add:
    path: /administrateur/categorie/add
    controller: App\Controller\DefaultController::categorie_add
categorie_delete:
    path: /administrateur/categorie/delete
    controller: App\Controller\admin\CategorieController::categorie_delete
souscategorie_add:
    path: /administrateur/souscategorie/add
    controller: App\Controller\DefaultController::souscategorie_add
souscategorie_delete:
    path: /administrateur/souscategorie/delete
    controller: App\Controller\admin\SousCategorieController::souscategorie_delete
addCategorie:
    path: /administrateur/categorie/addCategorie
    controller: App\Controller\admin\CategorieController::addCategorie
addPromo:
    path: /administrateur/promo/addPromo
    controller: App\Controller\admin\PromoController::addPromo
addSouscategorie:
    path: /administrateur/souscategorie/addSouscategorie
    controller: App\Controller\admin\SousCategorieController::addSouscategorie
addProduit:
    path: /administrateur/produit/addProduit
    controller: App\Controller\admin\AdminProduitController::addProduit

deleteProduit:
    path: /administrateur/produit/deleteProduit
    controller: App\Controller\admin\AdminProduitController::delProduit
